---
title: "File 1"
author: "David Henderson"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.width = 12, fig.height = 9,
                      warning = FALSE, message = FALSE)
```


# Introduction

This file shows the wrangling to raw files taken from: 

  1. The English place
  2. The Scottish one
  3. The Welsh one
  4. You guessed it...
  
These files are used to summarise the number of care homes in each nation and to calculate the total number of beds available. 

## Packages

R packages required.....

```{r}
library(tidyverse)
library(curl)
library(readxl)
library(forcats)
library(ggthemes)
library(here)
here()
#Helper function
`%nin%` <- negate(`%in%`)

#Short cut for csv output with html tables
my_datatable <- function(x){
  DT::datatable(x, extensions = "Buttons", options = list(dom = "Bfrtip", 
                                                          buttons = c("csv")))
}
```


# Care Home size


```{r}
eng <- read_xlsx(here("raw_data/ENGLAND_care_homes.xlsx"), sheet = "HSCA Active Locations")
scot <- read_xlsx(here("raw_data/SCOTLAND_care_homes.xlsx"), sheet = "MDSF_data_31 May 2020")
ni <- read_xlsx(here("raw_data/NI_care_homes.xlsx"))
w <- read_xlsx(here("raw_data/22 - CIW - 20200730 - list of adult care homes in Wales.xlsx"), 
               range = "A4:K1060")
```

```{r}
eng %<>% 
  filter(`Care home?` == "Y" & 
           `Location Inspection Directorate` == "Adult social care") %>% 
  select(`Location Name`, `Care homes beds`, `Service user band - Older People`) %>%
  #filter(!is.na(`Service user band - Older People`))
  mutate(country = "England")
my_datatable(eng)
```

```{r}
scot %<>% 
  filter(CareService == "Care Home Service" & 
           Subtype %nin% c("Children & Young People" ) &
           ServiceStatus == "Active") %>% 
  select(`Location Name` = ServiceName, 
         `Care homes beds` = TotalBeds, Subtype) %>% 
  mutate(country = "Scotland")
my_datatable(scot)
```

```{r}
ni %<>% 
  filter(Category %in% c("Nursing (NH)", "Residential (RC)")) %>%
  #filter(str_detect(`Categories of Care`, "I") | 
           #str_detect(`Categories of Care`, "E") |
           #str_detect(`Categories of Care`, "DE") |
          # str_detect(`Categories of Care`, "MP(E)") |
          # str_detect(`Categories of Care`, "LD(E)") |
          # str_detect(`Categories of Care`, "PH(E)")) %>% 
  select(`Location Name` = ServiceName,
         `Care homes beds` = `Max Approved Places`,
         `Categories of Care`) %>% 
  mutate(country = "Northern Ireland")
my_datatable(ni)
```

```{r}
w %<>% 
  select(`Location Name` = `Service Name`,
         `Care homes beds` = `Maximum Capacity`,
         `Service Sub Type`) %>% 
  mutate(country = "Wales")
my_datatable(w)
```




```{r}
uk <- bind_rows(eng, scot, w, ni) %>% 
  mutate(country = factor(country,
                          levels = c("England", "Scotland", "Wales", "Northern Ireland")))
my_datatable(uk)
```



```{r}
feather::write_feather(uk, here("derived_data/uk.feather"))
```

# [HOME PAGE](https://davidhen.github.io/ltc_covid_uk/index.html)

```{r}
devtools::session_info()
```


